### ISSUE TITLE
Add withLogger HOC

### ISSUE THREAD

**Issue by superpike** [superpike/kid-games#2]
Add new HOC _withLogger_.

- It should take parameters: 
    - array of lifecicle's names 
    - output stream (default console.log)
- It should output required logs.
- _withLogger(params)(Component)_
- use TDD approach in developing

**Comment by vbelolapotkov** [comment]
@superpike how about outlining your action plan, approach? Are params mentioned above going to be passed in such order? What do you think on the order?

**Comment by superpike** [comment]
@vbelolapotkov for now these are just declared unordered params. I'll think about order and kinds of params at the start of developing for sure.
