### ISSUE TITLE
Make eazy to read custom hook for theme context

### ISSUE THREAD

**Issue by superpike** [superpike/kid-games#3]
- remove reducer (no need for simple issues)
- divide current theme and change function
- make couple custom hooks:
    - only for theme value
    - for both: theme and change function

**Comment by vbelolapotkov** [comment]
@superpike how about changing the value of a label to `refactor`? I don't have a feeling that the current hook is invalid. It's rather not so friendly 🙂

**Comment by superpike** [comment]
Made changes without PR, seemed too eazy for PR. Next changes will be with PR.
[commit for this issue](https://github.com/superpike/kid-games/commit/905a0446bf3fb5889dfb698846a685bdfb5f4871)

**Comment by vbelolapotkov** [comment]
Ok. However, generally it’s a bad idea to make any changes without a PR.
